### ISSUE TITLE
Camera selection on phones

### ISSUE THREAD

**Issue by fitztrev** [uploadcare/uploadcare-widget#197]
If you select "Camera" from the sidebar list of sources, it defaults to using the front camera after you allow access to the camera. You're not able to switch.

However, if you hit "Choose a local file" and then select Camera from the system dialog that pops up, you're able to select which camera it uses.

Tested on 2 different Android phones: HTC DNA + Galaxy S3

**Comment by homm** [comment]
You are right. This can be unexpected for most of users, but is by design for now.

JS `getUserMedia` API is so weak and so different in different browsers so I'm thinking about hiding camera tab on mobile devices at all, and leave only more powerful native dialog, which is also more familiar to user. What do you think about this?

**Comment by fitztrev** [comment]
:+1:

**Comment by homm** [comment]
We decide to hide camera tab in mobile layout starting from widget version 2.2.0 (current version is 2.4.0). This should resolve the issue for phones. The problem is still there for tablets, but I don't see any ways to resolve it.
