### ISSUE TITLE
Uploadcare Widget is Flipping Images Sometimes

### ISSUE THREAD

**Issue by ksylvest** [uploadcare/uploadcare-widget#222]
For some reason the JS SDK is flipping my images some-times:

![screen shot 2015-05-08 at 4 16 36 pm](https://cloud.githubusercontent.com/assets/73432/7547263/8e2626fa-f59e-11e4-9d54-574e63142f28.png)

The asset appears fine everywhere else (UDID: a6f64b08-fe42-4d9b-bf25-a75121632b07). It appears with the correct orientation briefly (while the framework is loading?) and appears with the correct orientation when opening the cropper.

**Comment by homm** [comment]
@ksylvest, do you use any image operations for this preview? I suppose no. This is native image pixels order for this image. To automatically rotate image based on EXIF tags you need to use any of [image operations](https://uploadcare.com/documentation/cdn/#image-operations). The simples is `-/preview/`. But in your case you need relative small copy so you need something like `/scale_crop/WxH/center/` where W and H is preview size.

**Comment by ksylvest** [comment]
I don't have any image operations, but the image loads with the correct orientation initially - then the JS SDK seems to flip it). Here is the version I have in the DOM:

https://ucarecdn.com/a6f64b08-fe42-4d9b-bf25-a75121632b07/

Isn't this an SDK bug?

**Comment by ksylvest** [comment]
@homm Changed out my URL to: https://ucarecdn.com/a6f64b08-fe42-4d9b-bf25-a75121632b07/-/scale_crop/160x160/center/

Same thing is happening. The SDK is flipping the image...

**Comment by homm** [comment]
This can't be bug in JS SDK, because JS SDK doesn't display images. Browser display images.

Correct orientation for this image is applied by a browser when you load image from address bar. For historical reasons browsers doesn't fix orientation when you open it inside `<img>` tag. You can check this yourself, just put `<img src="https://ucarecdn.com/a6f64b08-fe42-4d9b-bf25-a75121632b07/">` anywhere on your page.

Uploadcare CDN automatically rotates images according EXIF tags if you use any image operation. So all you need is use processed image with any operations rather than original image in your preview.

**Comment by homm** [comment]
Kevin, as I understand, you are using custom JS code to show this preview. You need to change it to show processed image rather than original. If I'm wrong and this is some of our libraries or example from our site, please let me know, and I'll fix it.

**Comment by ksylvest** [comment]
@homm No, this is correct. It was definitely a bug on our end (didn't realize that the `onChange` callback is triggered initially). Thanks for the help!
