### ISSUE TITLE
Receive a hook or display a proper message when a validator fails

### ISSUE THREAD

**Issue by mikegleasonjr** [uploadcare/uploadcare-widget#377]
Seriously this leaves the user confused when a validator fails:

![2017-04-04 at 2 59 pm](https://cloud.githubusercontent.com/assets/1644534/24660396/52ea52f4-1947-11e7-9e21-46fb9f701bd9.png)

My client won't allow this kind of generic message and I will have to allow huge files to be uploaded.

**Comment by mikegleasonjr** [comment]
Used the crop parameter instead of a validator...

**Comment by mikegleasonjr** [comment]
Wait what? The huge original image is still stored and the url just contains the transformations applied ?

**Comment by dmitry-mukhin** [comment]
Mike,

1st, you may provide your own message when validation fails. For obvious reasons we can't have that in the widget :)
2nd, widget validation may work before or after file is completely uploaded. In case of local uploads, it's usually before. In general you need to keep track of files that are rejected by custom validation and remove them if they are stored in Uploadcare storage.

Please feel free to ask follow up questions.

**Comment by khazamov** [comment]
We are always working on improving our error messaging and documentation, but this is not a complicated case. In order to display a proper error message you need to:
1. Create a javascript Error object inside of your validator and pass appropriate message to constructor. 
2. Define detailed error message through [custom localization](https://uploadcare.com/documentation/widget/#custom-localization). 

[Here](http://codepen.io/uploadcare/pen/wJZvvL) is the demo that demonstrates above.
