### ISSUE TITLE
Should video recording be possible now in Safari 11.1?

### ISSUE THREAD

**Issue by weavermedia** [uploadcare/uploadcare-widget#490]
Until now video recording was not possible in Safari due to lack of support for APIs but according to CanIUse (https://caniuse.com/#feat=stream) Safari now supports getUserMedia/Stream API from 11.1 onwards.

Tested with widget 3.4.0 and Safari 11.1 and camera tab can only take photos.

Will video recording soon be possible?

**Comment by Zmoki** [comment]
@weavermedia Safari 11.1 supports Media Capture and Stream API. It's enough to start the stream from a webcam and take photos. But Safari 11.1 don't supports [Media Recorder API](https://caniuse.com/#feat=mediarecorder), so video/audio recording is not possible in Safari.

But on iOS Safari in the mobile view of the widget, we use [`input[capture]`](https://caniuse.com/#feat=html-media-capture) instead of streams, that provided direct access to a camera

![fullsizeoutput_62](https://user-images.githubusercontent.com/948688/41915443-677d3fe2-795e-11e8-9ef1-468b2d8a1da2.jpeg)

**Comment by weavermedia** [comment]
Great 👍Good to know exactly which API is required. Always like Apple to drag their feet 😕
