### ISSUE TITLE
Manual widget initialization does not use data-attributes

### ISSUE THREAD

**Issue by EdgarOrtegaRamirez** [uploadcare/uploadcare-widget#536]
When setting this global var
```js
UPLOADCARE_MANUAL_START = true;
```

and initializing widget manually
```js
var thumbnailPhotoUploader = uploadcare.SingleWidget('#image_uploader');
```

Data attributes are not used:
- clearable is not enabled
- existing value attribute from input value is not used
- widget renders empty
- cropping is not enabled

![upc](https://user-images.githubusercontent.com/2790520/56050172-c9528880-5d10-11e9-8ce8-aabe0f84962f.png)

_This does not happen for automatic initialization_

**Comment by nd0ut** [comment]
Hey @EdgarOrtegaRamirez 

Please check this codepen: https://codepen.io/anon/pen/BEqeZM
Does it work well on your end?

In any case, please provide more information: widget version, browser, code or minimal demo so that I can reproduce the problem.

I see that in your example code, the selector for id (`#image_uploader`) is different from what is shown in the screenshot (`#thumbnail_image_uploader`).

**Comment by EdgarOrtegaRamirez** [comment]
@nd0ut hey, took a look at your codepen and it worked as expected, I was using the latest version 3.7 and browser firefox but can't remember all the steps I did maybe the selector was wrong (?) I'm not sure, I'll close this now, Thanks for your time.
