### ISSUE TITLE
preferredTypes not working

### ISSUE THREAD

**Issue by luisrudge** [uploadcare/uploadcare-widget#547]
Even though I'm adding`preferredTypes`, it's not blocking other files from being selected.

```js
    const dialog = uploadcare.openDialog(initialFiles, null, {
      publicKey: process.env.REACT_APP_UPLOADCARE_KEY,
      multiple: true,
      preferredTypes: 'image/*'
    });
```

![image](https://user-images.githubusercontent.com/941075/61193226-7af6b200-a690-11e9-905c-dbcb5bb5b9b8.png)

![image](https://user-images.githubusercontent.com/941075/61193229-82b65680-a690-11e9-811e-f70a270d0b1b.png)

**Comment by optlsnd** [comment]
Hi @luisrudge, sorry for such a long delay with the response! The `preferredTypes` option implements different functionality. It tells social/cloud services APIs which file formats you'd like to receive. For example, by default, Google Drive API returns documents in PDF format, but with this option, you can force it to returns XLSX/DOCX instead. 

In order to hide unwanted file types in the system dialog, use the `inputAcceptTypes` [option](https://uploadcare.com/docs/file_uploads/widget/options/#option-input-accept-types). Note that it affects only local files, and users still can disable the filter and select any file. To prevent uploading files of unwanted type, size, etc. use [file validation](https://uploadcare.com/docs/file_uploads/widget/moderation/).
