### ISSUE TITLE
Camera tab is hidden on mobile layout

### ISSUE THREAD

**Issue by kabukki** [uploadcare/uploadcare-widget#795]
## Summary

On mobile devices, tabs are collapsed and only a few are displayed, along with a "..." button, as seen in this screenshot:

![image](https://user-images.githubusercontent.com/18421491/95058900-75074980-06f8-11eb-9655-50f2ba60e835.png)

Users struggle finding the "camera" tab, which is actually hidden in the dropdown accessed by the aforementioned "..." button:

![image](https://user-images.githubusercontent.com/18421491/95059047-a54ee800-06f8-11eb-892f-a263faf7937c.png)

I was wondering whether this behaviour was normal and if not, what could be done to improve the accessibility of the camera tab, possibly displaying it along with the other providers.

## Relevant information

Removing providers does not make the camera tab appear outside of the "..." menu, it is always hidden and needs 1 click to be accessible, making users think the option does not exist at first glance.

### Environment (if relevant)

- `uploadcare-widget`: `3.8.3`

Thank you!

**Comment by optlsnd** [comment]
Hi @kabukki, sorry for the radio silence! Unfortunately, there's no way to change the order of source icons in mobile view, but as a workaround, you can change the default order of tabs so that the camera tab comes first, and in this case, it will appear once a user has clicked the widget button. The order can be changed via the `data-tabs` option:

`<input type="hidden" role="uploadcare-uploader" name="my_file" id="uploadcare-file" data-tabs="camera file facebook gdrive instagram box vk"/>`

**Comment by kabukki** [comment]
Thanks, I've managed to use the camera source first, but I feel like the "back" or "menu" button is hidden behind the camera logo (the same behaviour happens with other sources), at first I thought I could not use another source 🤔 could it be fixed ?

![image](https://user-images.githubusercontent.com/18421491/100116550-2a8e8780-2e74-11eb-8872-cc199596fe9e.png)

**Comment by kabukki** [comment]
Any update on this menu issue ? Our users cannot find other ways to upload their files now... 😅

**Comment by optlsnd** [comment]
@kabukki I apologize for the delayed response! Normally, the icon should be displayed in the top-left corner of the dialog
![image](https://user-images.githubusercontent.com/13101080/102117235-2213e600-3e4f-11eb-950c-bb4e9c895538.png)
Did you add any custom CSS to style the uploader? If so, make sure there are no CSS rules that may affect the layout of the dialog window. If it's not the case, will you be able to share a link to the page with your uploader installation so that I can check it live?

**Comment by kabukki** [comment]
Hi ! There is no custom CSS that should impact the uploadcare component, and we are using the panel instead of the dialog, so maybe the behaviour is different ? Otherwise I'm thinking our widget is not up-to-date, but the changelog does not reveal anything major related to this issue.

Here is a link so you can see it live: https://debug.teester.com/casting/upload (you need to log in first, and access it from mobile view because the routes are different). The problem only happens in mobile view and when the viewport width is <= 759px.

**Comment by optlsnd** [comment]
Thank you! It looks like this CSS affects the layout. If it's removed, the hamburger menu icon is displayed properly at the top-left corner.

![image](https://user-images.githubusercontent.com/13101080/102216308-fd218080-3eeb-11eb-8548-73f9d1ba2d35.png)

**Comment by kabukki** [comment]
Woah, this was quite hard to spot ! Thank you a lot for the quick and efficient response 😄
