### ISSUE TITLE
No button on screen

### ISSUE THREAD

**Issue by sdcaulley** [uploadcare/uploadcare-widget#839]
## Summary
Using the CDN in a lit-element application.  I have set the script tag for the CDN in the head, and defined the `<input>` as described in the docs, but there is no button on the screen.  When I do an `inspect element` in the browser, I can see the input.

## Relevant information
I have also tried using the npm package, but get an `Uncaught SyntaxError: import not found: default`, when I use `import uploadcare from 'uploadcare-widget'`.

### Environment (if relevant)
lit-element: 2.4.0

**Comment by optlsnd** [comment]
Hi @sdcaulley, it might have something to do with the component lifecycle. It can be fixed by moving widget initialization to the `firstUpdated` callback. If this doesn't help, could you please share your code snippet or create a sandbox so that we can inspect your code live?

**Comment by optlsnd** [comment]
@sdcaulley, we're working on a new file uploader and would like to invite you to a closed beta test. If you're interested in participating in it, please, contact us at [hello@uploadcare.com](mailto:hello@uploadcare.com), and we'll provide further information.

**Comment by sdcaulley** [comment]
> Hi @sdcaulley, it might have something to do with the component lifecycle. It can be fixed by moving widget initialization to the `firstUpdated` callback. If this doesn't help, could you please share your code snippet or create a sandbox so that we can inspect your code live?

I am not sure how I would initialize the widget, since I am using the CDN.

**Comment by optlsnd** [comment]
Thanks for the info! The problem here is that the current implementation of the widget can't work with shadow DOM. We're working on a wrapper for web components, but I'm afraid I can't share an estimated release date yet. The easiest way to work around this issue is to disable shadow DOM on your lit-element component, however, this may affect the component functionality in some cases. Also, you can try to implement working with shadow DOM yourself. The idea behind this is to move the input and the style element added by the library to shadow DOM to make them visible to your component. The new uploader we're working on is compatible with web components and shadow DOM, so we're happy to invite you to test it out. We've received your request and added you to a list of beta testers. The test will start soon, and we'll be in touch with further instructions. Also, when the wrapper for the legacy uploader is ready, we'll let you know.

**Comment by sdcaulley** [comment]
@optlsnd Thank you for the information.
